### ISSUE TITLE
Corrupt and Missing Recordlabel Mediaflags

### ISSUE THREAD

**Issue by jeneral** [pix/aeon#126] opened 2010-09-01 01:59 UTC
I have noticed a few corrupt mediaflags and I also wanted to recommend a few additional ones. The new EMI flags all show up like this (see black square in bottom right):

http://a.imageshack.us/img832/5585/screenshot000ox.jpg

The odd thing is the picture shows up correctly everywhere but in XBMC. I restored an older copy of aeon and used its EMI flags in the meantime.

As well, the Sony Music Distribution.png flag isn't even a valid PNG.

I created a zip file from some of the other flags in aeon. These are some missing flags that show up in my library. The most obvious one is A&M. A&M is included with aeon but it is called AM.png and most artists don't recognize it.

http://www.mediafire.com/?b6007r8hksvsa9c

**Comment by pix** [comment] 2010-09-01 18:32
Sony Music Distribution.png it is on linux.... The problem is that Windows Version of Git doesn't support symbolic links (works fine on Linux).

But this has been fixed, Closing...

**Closed as completed by pix** 2010-09-01 18:32 UTC
