### ISSUE TITLE
Showcase - Navigating Right In Tv Show Episodes - Doesn't Hide Dialog

### ISSUE THREAD

**Issue by mark007** [pix/aeon#99] opened 2010-08-20 17:50 UTC
Hi, just a minor observation. In showcase at least, when navigating left or right in movies, or in tv show seasons, the information box above the little posters will slide off the screen BUT in tv show episodes, navigating to the right doesn't slide if off the screen..

Not a big issue just a matter of consistency.

**Comment by pix** [comment] 2010-08-22 21:29
Are you sure ? I can't reproduce this.

**Comment by mark007** [comment] 2010-08-22 23:10
Ahh sorry, I actually have "landscape" set as the view for tv show episodes. Maybe you can reproduce with this..

**Comment by pix** [comment] 2010-08-23 08:11
Closed by 5b030ed8885c7bf30da12457dc0d3e920cb2aa36: Showcase - Navigating Right In Tv Show Episodes - Doesn't Hide Dialo

**Closed as completed by pix** 2010-08-23 08:11 UTC
Labels: Bug, Not Confirmed
