### ISSUE TITLE
Cannot return to Video Window on main screen using remote/keyboard. Must use mouse to click on the wndow

### ISSUE THREAD

**Issue by kin0kin** [pix/aeon#11] opened 2010-07-08 03:46 UTC

**Comment by mindweaver** [comment] 2010-07-08 10:39
No really following you here. please tell me how to reproduce.

**Comment by kin0kin** [comment] 2010-07-08 12:12
Play a movie then go back to main menu. Make sure in Settings you have set it to show video window on main menu.

At the main menu, you can see the video either at the bottom/top left. There's no way to return to the movie without using the mouse to click on the window. This also seems to be a problem with some other skins. However, in Confluence, you can keep hitting down until it highlights the video, then you can hit enter and relaunch the video at full screen.

Proposed solution: consider adding an ondown command somewhere in the main menu when video window is activated so that users can scroll down to the video and relaunch it to full screen.

**Comment by mindweaver** [comment] 2010-07-08 14:19
Works for me. Just hit TAB and you are back.

**Comment by pix** [comment] 2010-07-08 14:56
Used to works for me too using my remote, not sure why it would have been broke with latest svn. I'll test that in the afternoon

**Comment by chanders** [comment] 2010-07-08 14:56
^^ Same here. But kin0kin's suggestion for a dedicated command is good too.

**Comment by mindweaver** [comment] 2010-07-08 14:59
there is a dedicated command. TAB. works on keyboard and is bound to my remote. same command you use to switch from music to vis and so on :) closing this now!

**Closed as completed by mindweaver** 2010-07-08 14:59 UTC
Labels: Bug, Rejected
