### ISSUE TITLE
Videos List view shows 2 poster images on top of each other

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#109] opened 2010-08-27 08:58 UTC
Steps:
1) I navigate into Videos
2) I navigate into my "TV" source (Which has a poster.jpg, folder.jpg, etc)
3) I navigate down to one of the shows, only highlighting it (Which all have their own poster.jpg, folder.jpg, etc)
Result: To the right of the list there are now 2 images displayed-- the poster.jpg from step 2 and poster from the show I highlighted in step 3 peaking out behind it.

**Comment by temmi2000** [comment] 2010-08-27 09:13
which viewtype? did it appear after a specific commit?

**Comment by sialivi** [comment] 2010-08-27 11:14
List viewtype, I'm not sure which comit but it must have been very recent

**Comment by temmi2000** [comment] 2010-08-27 15:13
cannot reproduce it. screenshot?

**Comment by sialivi** [comment] 2010-08-27 18:14
I'll snap a screenshot in a moment.

Forgot to mention that if I press left, which moves focus to the scrollbar, the top image disappear and only the image that is supposed to show remains.

**Comment by sialivi** [comment] 2010-08-27 18:32
The tvshow's image is can be seen poking out behind the parent folders poster.jpg and in the floor reflection:

http://img822.imageshack.us/i/listbug1.jpg/

Pressing Left reveals the image:

http://img829.imageshack.us/i/listbug2.jpg/

**Comment by phil65** [comment] 2010-08-27 19:01
You have all your tvshows in seperate folders?
your "TV" source shouldnt have a poster.jpg and/or folder.jpg, these files should only be in [TVSHOWSOURCE] / [NAME OF TVSHOW]

**Comment by sialivi** [comment] 2010-08-27 20:47
I know it's not _needed_ but it has never been a problem having them before. I like having custom art for all my sources.

**Comment by phil65** [comment] 2010-09-11 01:27
is this bug still there?

**Comment by sialivi** [comment] 2010-09-11 01:41
Yes, it's still there

**Comment by phil65** [comment] 2010-09-28 09:50
fixed in font_rework I think

**Closed as completed by phil65** 2010-09-28 09:50 UTC
