### ISSUE TITLE
Showcase View in Music

### ISSUE THREAD

**Issue by jeneral** [pix/aeon#78] opened 2010-08-08 13:30 UTC
There are a few issues when using this view in music:
- If info panel is set to 'trigger', every up press on the remote opens the sidebar config as well.
- Showcase labels Years Active, Formed and Styles are blank.

A few suggestions as well:
- For artists that have an icon but don't have fanart, the Info Panel should display the icon instead of nothing.
- Artist Icons are sometimes not the same aspect ratio (stretched and fat faces). Maybe an option to 'crop' icons would be nice.

**Comment by pix** [comment] 2010-08-08 13:32
Can you post screenshots explaining you problems please ?

> For artists that have an icon but don't have fanart, the Info Panel should display the icon instead of nothing.

You mean if the artist havve a fanart but no icon ?

> If info panel is set to 'trigger', every up press on the remote opens the sidebar config as well.

Which view ? Showcase ?

**Comment by jeneral** [comment] 2010-08-08 19:17
Here is an artist with fanart in showcase view:
http://a.imageshack.us/img685/3663/artistwithfanart.jpg

Here is an artist without fanart in showcase view:

http://a.imageshack.us/img198/8065/artistwithoutfanart.jpg

Both artists have icons because I used the last.fm scraper for their icons. Unfortunately the aspect ratio varies between pics thus the 4th suggestion I made originally.

You can also see the missing fields in these pics. Pressing Info for an artist does show the fields correctly.

http://a.imageshack.us/img10/6584/artistinfo.jpg

FYI. All these pics are taken in Library mode.

**Comment by pix** [comment] 2010-08-09 06:48
> You can also see the missing fields in these pics. Pressing Info for an artist does show the fields correctly.

This is already fixed :-)

**Comment by jeneral** [comment] 2010-08-09 19:39
Are you saying the Showcase view labels (formed, years active, styles) are fixed? I just ran a git update and the aforementioned  values are still blank. They do show up correctly in Low List view mode but not in Showcase view mode.

**Comment by pix** [comment] 2010-08-09 21:46
Working for me: http://i.imgur.com/sv7ga.jpg, Are you sure your copy is up to date ? Which revision are you using ?

**Comment by jeneral** [comment] 2010-08-09 23:23
I don't know how to find the version number. I just followed the instructions and downloaded Aeon65 using GIT the other day. I ran GIT update today to see if the issue was fixed with no luck. I will delete my Aeon repository and re-download it to see if something went wrong the first time.

**Comment by jeneral** [comment] 2010-08-10 00:09
OK, I deleted my aeon and re-downloaded it. That fixed the missing info fields and the aspect ratio in thumbnails. This time I followed a different set of instructions.

It would still be nice to have the icon/thumbnail show when an artist doesn't have fanart instead of a big gray background.

A few other suggestions:
- When playing back in visualization mode, give the option of having info clear all text. The text can briefly appear when the next song starts playing (a la Confluence).
- Some solo artists don't have a 'Formed' field. In those cases, Confluence substitutes the 'Formed' field for the 'Born' field. 
- S normally brings up the shutdown menu (I have a remote key mapped for it). In Aeon65 it also brings up a menu but 'Exit XBMC' isn't the default. It would be nice to have it consistent with other skins.

**Comment by pix** [comment] 2010-08-10 06:05
> It would till be nice to have the icon/thumbnail show when an artist doesn't have fanart instead of a big gray background.

Done.

**Comment by pix** [comment] 2010-08-10 19:51
Closed by 080d8f3e8f8a24dcdcfa10777b0c336778143bdb: Showcase View in Music

Added Formed/Born failover for artists

**Closed as completed** 2010-08-11 02:51 UTC
Labels: Bug, Confirmed

**Comment by jeneral** [comment] 2010-08-11 03:15
Excellent work. The icon/thumbnail does exhibit a few glitches. Since thumbs in place of fanart are much smaller, wouldn't it be better to have them centered instead of cropped to fit the aspect ratio? Cropping a small thumb can look weird in some cases:

http://yfrog.com/cbscreenshot000hj

When browsing the library by year, this change results in albums being inserted in place of the artists (I don't know if that was intended):

http://yfrog.com/e4screenshot001lxj

I have also run across a new bug when browsing the library by year. If after selecting a year, it shows up in list mode, showcase is not selectable. I have to choose multiwall to enable showcase view mode.

**Comment by pix** [comment] 2010-08-11 05:50
> When browsing the library by year, this change results in albums being inserted in place of the artists (I don't know if that was intended):

I can't seems to be able to reproduce this one more details ?

> I have also run across a new bug when browsing the library by year. If after selecting a year, it shows up in list mode, showcase is not selectable. I have to choose multiwall to enable showcase view mode.

You mean you've been able to access the real showcase view ? Showcase has been removed from years views as it was not completly working.

**Comment by jeneral** [comment] 2010-08-11 16:47
Once again, great work on removing the crop from the Showcase view's thumbs-as-fanart. I just tried it today and it looks fantastic!

re: your first question. From the main menu, I open music and select 'Years'. The years are listed in 'List' view and then I select a year. Then if I select an artist that DOESN'T have fanart, a picture of the album cover shows up in its place. Any artist that does have fanart will show the artist image/fanart.

Here is 1994 in Showcase view for an Artist (Chilliwack) that doesn't have fanart:
http://a.imageshack.us/img839/834/screenshot002ly.jpg

I don't understand your second question. The actual years are listed in list view. Once a year is selected is when the glitch appears. Unfortunately, this glitch doesn't appear 100% of the time. I can occasionally reproduce the problem if I change a year to list view, go back to the years list, re-enter said year and try to get back to Showcase view. Sometime the Showcase view won't be one of the options. In those cases, I select Multiwall and it switches to Showcase view.

There is another small issue with Showcase view that only appears in the music section. I use page up and page down a lot to scroll between pages. In Movies or TV, page up or down works as intended. In Music, a page up or page down will skip a few albums (2 on either side). I guess it is because Showcase view for albums can only display 5 albums at a time vs. 7 movie covers for Showcase in movies.

**Comment by pix** [comment] 2010-08-11 17:28
> Then if I select an artist that DOESN'T have fanart, a picture of the album cover shows up in its place.

I use the thumbnail as fallback when there's no fanart available.

I'd like to have a reproducible testcase in order to fix the second problem, I can't reproduce it.
